config/routes.rb
require "sidekiq/web"
Rails.application.routes.draw do
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  devise_for :users
  devise_for :admins
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'dashboards#dashboard'

  namespace :admins do
    get :dashboard
    resources :loan, only: [] do
      patch :update
      post :reject_loan
    end
  end

  namespace :users do
    get :dashboard
  end

  resources :loans, only: [:new, :create] do
    post :confirm_request
    post :reject_request
    post :repay_loan
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :loans, dependent: :destroy

  validates :name, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/loan.rb
class Loan < ApplicationRecord
  belongs_to :user
  belongs_to :admin

  validates :amount, presence: true, numericality: {greater_than: 0}
  validates :interest_rate, presence: true, numericality: {greater_than_or_equal_to: 0}
  validate :amount_cannot_exceed_wallet, on: :create

  enum state: [:requested, :approved, :open, :closed, :rejected]

  def calculate_interest
    update(amount: amount + (amount * interest_rate/100))
  end

  def process_loan
    if amount > user.wallet
      admin.update(wallet: (admin.wallet + user.wallet))
      user.update(wallet: 0)
      update(state: "closed")
    end
  end

  private

  def amount_cannot_exceed_wallet
    if amount.present? && amount > user.wallet
      errors.add(:amount, "cannot exceed the user's wallet amount")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :loans, dependent: :destroy

  validates :name, presence: true
end

app/controllers/admins/loan_controller.rb
class Admins::LoanController < ApplicationController
  before_action :authenticate_admin!

  def update
    @loan = current_admin.loans.find(params[:loan_id])
    if @loan.update(loan_params)
      redirect_to admins_dashboard_path
    end
  end

  def reject_loan
    @loan = current_admin.loans.find(params[:loan_id])
    if @loan.update(state: 3)
      redirect_to admins_dashboard_path
    end
  end

  protected

  def loan_params
    params.require(:loan).permit(:interest_rate, :state)
  end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_action :authenticate_admin!

  def dashboard
    @loan_requests = current_admin.loans.where(state: [0, 1, 2, 3]).includes(:user)
    @wallet = current_admin.wallet
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

  def dashboard

  end
end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  before_action :authenticate_user!
  before_action :set_loan, only: [:confirm_request, :reject_request, :repay_loan]

  def new
    @loan = current_user.loans.build
  end

  def create
    @loan = current_user.loans.build(loan_params)
    if @loan.save
      redirect_to users_dashboard_path
    else
      render :new, status: :unprocessable_entity
    end

  end

  def confirm_request
    @loan.admin.update(wallet: @loan.admin.wallet - @loan.amount)
    current_user.update(wallet: current_user.wallet + @loan.amount)
    @loan.update(state: 2)
    redirect_to users_dashboard_path
  end

  def reject_request
    @loan.update(state: 4)
    redirect_to users_dashboard_path
  end

  def repay_loan
    current_user.update(wallet: current_user.wallet - @loan.amount)
    @loan.admin.update(wallet: (@loan.admin.wallet + @loan.amount))
    @loan.update(state: 3)
    redirect_to users_dashboard_path
  end

  protected

  def loan_params
    params.require(:loan).permit(:amount, :admin_id, :state)
  end

  def set_loan
    @loan = current_user.loans.find(params[:loan_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def dashboard
    @loans = current_user.loans.where(state: [1, 2, 3])
    @wallet = current_user.wallet
  end
end

app/helpers/admins/loan_helper.rb
module Admins::LoanHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/dashboard.html.erb
<h1>Admin Dashboard</h1>
<div><%= button_to('Logout', destroy_admin_session_path, :method => :delete) %></div>
<h4>Wallet: <%= @wallet %> Rs</h4>
<% if @loan_requests.present? %>
  <h2>Loan requests</h2>
  <% @loan_requests.each do |loan_request| %>
    <p>
    <%= form_with scope: loan_request, url: admins_loan_update_path(loan_request.id), method: :patch do |form| %>
      <%= form.hidden_field :state, value: "approved" %>
      <div>
          <div>User name: <%= loan_request.user.name %></div>
          <div>State: <%= loan_request.state %></div>
          <div>Interest rate: <%= form.number_field :interest_rate %> %</div>
          <div>Amount: <%= loan_request.amount.round(2) %> Rs</div>
          <% if loan_request.state == "requested" %>
            <span><%= form.submit "Approve loan" %></span>
          <% end %>
        </div>
    <% end %>
    <% if loan_request.state == "requested" %>
      <div><%= button_to "Reject", admins_loan_reject_loan_path(loan_request.id), method: :post, class: "test" %></div>
    <% end %>
    </p>
    <br/>
    <% end %>
<% else %>
  <div> No loan Request</div>
<% end %>

app/views/dashboards/dashboard.html.erb
<h1>Select role to login</h1>

<div>
  <%= link_to "Admin login", admins_dashboard_path %>
</div>
<br/>
<div>
  <%= link_to "User login", users_dashboard_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LendingMoneySystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/loans/new.html.erb
<h1>Create loan request</h1>
<%= form_with model: @loan do |form| %>
  <%= form.hidden_field :state, value: "requested" %>
  <div>
    <%= form.label :amount %>
    <%= form.number_field :amount %>
    <% @loan.errors.full_messages_for(:amount).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <br/>
  <div>
    <%= form.label :Lender %>
    <%= select("loan", "admin_id", Admin.all.collect {|admin| [admin.name, admin.id]}) %>
  </div>
  <br/>
  <div><%= form.submit %></div>
<% end %>

app/views/users/dashboard.html.erb
<h1>User Dashboard</h1>
<div><%= button_to('Logout', destroy_user_session_path, :method => :delete) %></div>
<div>
  <%= link_to 'Request Loan', new_loan_path %>
</div>
<h4>Wallet: <%= @wallet %> Rs</h4>
<% if @loans.present? %>
  <h2>Loans</h2>
  <table>
    <thead>
    <tr>
      <th>User</th>
      <th>Interest rate</th>
      <th>Amount</th>
      <th>state</th>
      <th>Action</th>
    </tr>
    </thead>
    <tbody>
    <% @loans.each do |loan| %>
      <tr>
        <td><%= loan.user.name %></td>
        <td><%= loan.interest_rate %> </td>
        <td><%= loan.amount.round(2) %> Rs</td>
        <td><%= loan.state %></td>
        <% if loan.state == "approved" %>
          <td><div><%= button_to "Confirm request", loan_confirm_request_path(loan.id), method: :post %></div></td>
          <td><div><%= button_to "Reject request", loan_reject_request_path(loan.id), method: :post %></div></td>
        <% elsif loan.state == "open"%>
          <td><div><%= button_to "Repay Loan", loan_repay_loan_path(loan.id), method: :post %></div></td>
      <% end %>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <div> No loans</div>
<% end %>